name: SpeedRoads
version: '${project.version}'
main: top.ellan.speedroads.SpeedRoads
api-version: '1.21.11'
authors: [Ellan]
description: 高性能道路加速插件

commands:
  speedroads:
    description: 重载插件配置
    usage: /speedroads reload
    aliases: [sr]
    permission: speedroads.admin

permissions:
  speedroads.admin:
    description: 管理员权限
    default: op