name: Java CI with Maven (Auto Artifact Upload)

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      # clean package 会生成 JAR 包
      run: mvn -B clean package --file pom.xml

    - name: Upload Artifact
      # 这个步骤负责将打包好的 JAR 上传到 GitHub Actions 页面
      uses: actions/upload-artifact@v4
      with:
        name: SpeedRoads-Plugin
        path: target/*.jar
        if-no-files-found: error
